# Generated by Django 2.2.7 on 2020-03-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_pnu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='concept',
            field=models.TextField(max_length=500, verbose_name='본인은 멋쟁이사자처럼 동아리내 어떤 캐릭터일지 서술하시오(최대 500자)'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='experience',
            field=models.TextField(max_length=1000, verbose_name='프로그래밍 경험이 있다면 기술스택과 수준을, 프로그래밍 경험이 없다면 기대감과 각오를 적어주세요'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='goal',
            field=models.TextField(max_length=500, verbose_name='코딩을 배워서 무엇을 하고 싶은지 구체적으로 서술하시오(최대 500자)'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='interview',
            field=models.TextField(max_length=255, verbose_name='면접가능시간( 3월 28일(토), 3월 29일(일) )을 작성해주세요'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='introduce',
            field=models.TextField(max_length=1000, verbose_name='자기소개 및 지원동기(최대 1000자)'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='plan',
            field=models.TextField(max_length=500, verbose_name='향후 1년계획 (학생회,동아리,아르바이트 등 최대 500자)'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='portfolio',
            field=models.FileField(blank=True, upload_to='portfolio/', verbose_name='본인을 나타낼 수 있는 포트폴리오를 첨부해주세요(URL의 경우 캡쳐후 첨부)(선택)'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='position',
            field=models.TextField(max_length=500, verbose_name='기획자/개발자/디자이너 중 가장 본인에게 가깝다고 생각하는 것을 고르고, 관련 근거를 서술하시오(최대 500자)'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='schedule',
            field=models.TextField(max_length=1000, verbose_name='1학기 고정스케줄(요일&시간)'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='team',
            field=models.TextField(max_length=500, verbose_name='참여했던 팀 활동 중 가장 기억에 남는 경험과 느낌점을 서술하시오(최대500자)'),
        ),
    ]
