# Generated by Django 2.2.7 on 2020-03-06 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apply_pnu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.TextField(max_length=1000, verbose_name='자기소개')),
                ('position', models.TextField(max_length=500, verbose_name='역할상상')),
                ('goal', models.TextField(max_length=500, verbose_name='목표')),
                ('plan', models.TextField(max_length=500, verbose_name='계획')),
                ('team', models.TextField(max_length=500, verbose_name='팀활동')),
                ('concept', models.TextField(max_length=500, verbose_name='컨셉')),
                ('portfolio', models.FileField(blank=True, upload_to='portfolio/', verbose_name='포폴')),
                ('interview', models.TextField(max_length=255, verbose_name='면접')),
                ('experience', models.TextField(max_length=1000, verbose_name='경험')),
                ('schedule', models.TextField(max_length=1000, verbose_name='고정스케줄')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='ApllyForm',
        ),
    ]
