# Generated by Django 2.2.7 on 2020-03-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply_pnu', '0002_auto_20200307_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apply_pnu.Profile'),
        ),
    ]
