# Generated by Django 2.1.1 on 2020-03-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_pnu', '0004_auto_20200308_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='portfolio',
            field=models.FileField(blank=True, upload_to='portfolio/', verbose_name='본인을 나타낼 수 있는 포트폴리오를 첨부해주세요(URL의 경우 캡쳐후 첨부)(선택사항)'),
        ),
    ]
