# Generated by Django 2.2.7 on 2020-12-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_pnu', '0006_auto_20200310_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='portfolio',
            field=models.FileField(blank=True, upload_to='portfolio/', verbose_name='본인을 나타낼 수 있는 포트폴리오를 첨부해주세요 ( URL의 경우 캡쳐후 첨부 )'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='team',
            field=models.TextField(max_length=500, verbose_name='참여했던 팀 활동 중 가장 기억에 남는 경험과 느낀점, 그리고 본인의 캐릭터는 무엇이었는지 작성해주세요 ( 최대500자 )'),
        ),
    ]
